# Flutter build
trigger:
- develop
jobs:
  - job: Android
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'latest'

    - task: CmdLine@2
      inputs:
        script: 'C:\hostedtoolcache\windows\Flutter\1.17.4-stable\windows\flutter\bin\flutter.bat pub get'
    - task: CmdLine@2
      inputs:
        script: 'C:\hostedtoolcache\windows\Flutter\1.17.4-stable\windows\flutter\bin\flutter.bat pub run build_runner build --delete-conflicting-outputs'
    - task: CmdLine@2
      inputs:
        script: 'C:\hostedtoolcache\windows\Flutter\1.17.4-stable\windows\flutter\bin\flutter.bat build aot'
    - task: CmdLine@2
      inputs:
        script: 'C:\hostedtoolcache\windows\Flutter\1.17.4-stable\windows\flutter\bin\flutter.bat analyze'
    - task: CmdLine@2
      inputs:
        script: 'C:\hostedtoolcache\windows\Flutter\1.17.4-stable\windows\flutter\bin\flutter.bat test --coverage'
