# Flutter build

trigger:
- develop
jobs:
  - job: Android
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'latest'
    
    - task: CmdLine@2
      inputs:
        script: 'C:\hostedtoolcache\windows\Flutter\1.17.3-stable\windows\flutter\bin\flutter.bat pub run build_runner build --delete-conflicting-outputs'


    - task: FlutterBuild@0
      inputs:
        target: apk