name: polis
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  intl: ^0.16.1
  flutter_bloc: ^3.2.0
  bloc: ^3.0.0
  simple_router: ^0.1.0
  equatable: ^1.1.1
  json_serializable: ^3.3.0
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  get_it: ^4.0.1
  shared_preferences: ^0.5.6+3
  image_picker: ^0.6.4
  url_launcher: ^5.4.2
  admob_flutter: ^0.3.4

  # Utils
  diacritic: ^0.1.1
  uuid: ^2.0.4
  tuple: ^1.0.3
  screenshot: ^0.1.1
  esys_flutter_share: ^1.0.2

  # Firebase
  cloud_firestore: ^0.13.4+2
  google_sign_in: ^4.4.1
  firebase_auth: ^0.15.5+3
  firebase_storage: ^3.1.5
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3+3
  firebase_performance: ^0.3.1+8

  # UI
  fancy_shimmer_image: ^1.0.1
  font_awesome_flutter: ^8.8.1
  introduction_screen: ^1.0.8
  smart_select: ^3.0.3
  flutter_grid_delegate_ext: ^0.0.2
  sliding_panel: ^1.0.3
  skeleton_text: ^1.0.0
  grouped_list: ^2.3.0
  flare_splash_screen: ^3.0.1
  flare_loading: ^2.1.1
  animated_text_kit: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator: ^0.7.0+2

  # Tests
  test: ^1.9.4
  bloc_test: ^4.0.0
  mockito: ^4.1.1
  image_test_utils:
    git: 'https://github.com/MarcinusX/image_test_utils'

  # Linting
  effective_dart: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Philosopher
      fonts:
        - asset: assets/fonts/Philosopher/Philosopher-Regular.ttf
        - asset: assets/fonts/Philosopher/Philosopher-Bold.ttf
          weight: 700
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700