name: polis
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  flutter_bloc: ^3.2.0
  bloc: ^3.0.0
  get: ^1.10.5
  simple_router: ^0.0.3+2
  equatable: ^1.1.0
  json_serializable: ^3.2.5
  uuid: ^2.0.4
  sailor: ^0.6.0
  get_it: ^4.0.0

  ## Firebase
  cloud_firestore: ^0.13.4
  firebase_auth: ^0.15.5+2
  google_sign_in: ^4.1.4
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3
  firebase_admob: ^0.9.1+3

  # UI
  getflutter: ^1.0.9
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

  # Tests
  test: ^1.9.4
  bloc_test: ^4.0.0
  mockito: ^4.1.1

  # Linting
  effective_dart: ^1.2.1

flutter:

  uses-material-design: true
