name: polis
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  flutter_bloc: ^3.2.0
  bloc: ^3.0.0
  get: ^1.8.1
  equatable: ^1.1.0
  cloud_firestore: ^0.13.2+1
  firebase_auth: ^0.15.4
  json_serializable: ^3.2.5

  # UI
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
